name: Dashboard Sync

on:
  push:
    branches: [ main ]

jobs:
  echo-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display README link
        run: |
          echo "✅ Dashboard link:"
          grep -i "https://" README.md
